version: '3.8'

services:
  WarDosPem-app:
    image: ghcr.io/mikhael20-tech/project-web:latest
    container_name: WarDosPem-service
    restart: always
    expose:
      - "3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env

  caddy:
    image: caddy:latest
    container_name: caddy-service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from wardospem.tech --to WarDosPem-app:3000
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - WarDosPem-app

volumes:
  caddy_data:
  caddy_config:
