version: '3.8'

services:
  wardosen-app:
    image: ghcr.io/mikhael20-tech/project-web:latest
    container_name: wardosen-service
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env
