version: '3.8'

services:
  wardosen-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wardosen-service
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_URL=${APP_URL}
      - REDIS_URL=${REDIS_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - FONNTE_TOKEN=${FONNTE_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    env_file:
      - .env
