[build]
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "NODE_ENV=production tsx server.ts"
preDeployCommand = "npx prisma generate && npx prisma db push --accept-data-loss"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
