import fs from 'fs';
let content = fs.readFileSync('src/App.tsx', 'utf-8');
content = content.replace(/indigo-600/g, 'teal-500');
content = content.replace(/indigo-500/g, 'teal-500');
content = content.replace(/indigo-400/g, 'teal-400');
content = content.replace(/indigo-300/g, 'teal-300');
content = content.replace(/indigo-200/g, 'teal-200');
content = content.replace(/indigo-100/g, 'teal-100');
content = content.replace(/indigo-50/g, 'teal-50');
content = content.replace(/indigo-700/g, 'teal-600');
content = content.replace(/indigo-800/g, 'teal-700');
content = content.replace(/purple-600/g, 'orange-500');
content = content.replace(/purple-500/g, 'orange-400');
content = content.replace(/purple-400/g, 'orange-400');
content = content.replace(/purple-100/g, 'orange-100');
content = content.replace(/purple-200/g, 'orange-200');
content = content.replace(/bg-\[#F8FAFC\]/g, 'bg-[#F0FAF8]');
content = content.replace(/slate-950/g, 'teal-950');
content = content.replace(/blue-400/g, 'yellow-400');
content = content.replace(/blue-200/g, 'yellow-200');
content = content.replace(/blue-50/g, 'yellow-50');
content = content.replace(/blue-100/g, 'yellow-100');
content = content.replace(/blue-600/g, 'yellow-500');
fs.writeFileSync('src/App.tsx', content);
console.log('Colors replaced successfully!');
